### ISSUE TITLE
Liquidity Pool on Uniswap

### ISSUE THREAD

**Issue by VictorOkodi** [scroll-tech/scroll-zkevm#111]
When trying to Add a Pool on Uniswap testing the Scroll Alpha Testnet
The Selecting of the Pair is not working as it is selecting only one token rather than the Usual two tokens
Could be because of a Bug or Congestion

**Comment by OrestTa** [comment]
@Turupawn

**Comment by sr-0007** [comment]
Uniswap showing me Scroll as  unsupported network.

**Comment by OrestTa** [comment]
> Uniswap showing me Scroll as unsupported network.

Are you on Alpha? (NOT Pre-Alpha)

<img width="835" alt="image" src="https://user-images.githubusercontent.com/830847/223764108-95d2f1d9-e9b9-4d2e-9ded-14a13665e313.png">

**Comment by Turupawn** [comment]
Hey @denominatedmhd please move this issue to the Scroll V3 repo:
https://github.com/scroll-tech/uniswap-v3-interface
I will close this and help you there
Cheers!
